# keystore_config.yaml

debug:
  keystore: ".android/debug.keystore"
  alias: "androiddebugkey"
  storePassword: "android"
  keyPassword: "android"

release:
  keystore: "release.keystore"
  alias: "processpath"
  storePassword: "atulgv92"
  keyPassword: "atulgv92"