name: processpath
description: A new Flutter project for managing processes, entries, and points with timeline and backup support.
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.5.0
  image_picker: ^1.0.4
  audioplayers: ^5.0.0

  # Firebase core + Firestore
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.3
  firebase_auth: ^6.1.0
  google_sign_in: ^6.1.4

  # Hive for local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

  # Notifications + timezone
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  connectivity_plus: 4.0.2

  # UI and routing
  go_router: ^13.0.0
  cupertino_icons: ^1.0.8
  timeline_tile: ^2.0.0
  reorderables: ^0.6.0

  # Utility packages
  uuid: ^4.1.0

  #pdf saver
  pdf: ^3.10.4
  file_picker: ^8.0.0

  #text animation and themes
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter_local_notifications:
  path: packages/flutter_local_notifications

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/log.png"
  adaptive_icon_background: "#FFFFFF"   # or your brand color
  adaptive_icon_foreground: "assets/icons/log.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google_logo.png
    - assets/icons/
    - assets/sounds/click.wav
    - assets/sounds/alert.wav
    - assets/sounds/done.mp3
    - assets/sounds/dialog.wav
    - assets/sounds/tick.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf